module.exports.location = "SAN";
module.exports.kinetIP = "10.4.97.107";
module.exports.server = "http://localhost:3000";
module.exports.num_screenshots = 50; //defines resolution of video played on lights
module.exports.num_lights = 50;
module.exports.output_height = 9;
module.exports.output_width = 5;
module.exports.PATH_NAME = '/Users/lasher/Sosolimited/PiPlayer/immediate_play/exported/';
// module.exports.PATH_NAME = 'exported';
